### ISSUE TITLE
Add use logger inside test class for power mock

### ISSUE THREAD

**Issue by paweltarkowski** [paweltarkowski/testing-examples#33]
As a developer please add logger with Logger.getLogger(....class) and test it for powermock class.

Verify if similar case observed here https://github.com/mockito/mockito/issues/1562

```
java.lang.IllegalAccessError: class javax.xml.parsers.FactoryFinder (in unnamed module @0x6dd79214) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x6dd79214
at javax.xml.parsers.FactoryFinder.(FactoryFinder.java:69)
at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:140)

```

**Comment by paweltarkowski** [comment]
no need ingore - no errors in logs
